version: "3"

services:
  productdb:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my8charspassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
