version: "3"
services:
  redis:
    image: redis
    ports:
    - 6379:6379

  service:
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 6
    environment:
      - SPRING_REDIS_HOST=redis