version: "3"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#  create database mydatabase;
#  use mydatabase;
#
#  CREATE USER 'user'@'%' IDENTIFIED BY 'password';
#  GRANT ALL ON mydatabase.* TO 'user'@'%';
